readme: README.md
authors:
- blue2cat
description: An Ansible role to deploy WeeWX automatically
license_file: LICENSE
tags:
  - weewx
repository: https://github.com/blue2cat/weewx-ansible
documentation: https://github.com/blue2cat/weewx-ansible/wiki
homepage: https://github.com/blue2cat/weewx-ansible
issues: https://github.com/blue2cat/weewx-ansible/issues