namespace: blue2cat
name: weewx
version: 0.1.1
readme: README.md
authors:
- blue2cat
description: Ansible role to install WeeWX
license_file: LICENSE
tags:
  - weewx
repository: https://github.com/blue2cat/weewx-ansible
documentation: https://github.com/blue2cat/weewx-ansible/wiki
homepage: https://github.com/blue2cat/weewx-ansible
issues: https://github.com/blue2cat/weewx-ansible/issues