license_file: LICENSE
tags:
  - weewx
documentation: https://github.com/blue2cat/weewx-ansible/wiki
homepage: https://github.com/blue2cat/weewx-ansible
issues: https://github.com/blue2cat/weewx-ansible/issues