---

#- include_vars: secrets.yml
- include_vars: group_vars/all

- name: add {{ weewx_user }} user
  user:
    name: "{{ weewx_user }}"
    shell: /bin/bash
    state: present

- name: download weewx binary
  get_url:
    url: http://weewx.com/downloads/weewx-{{ weewx_version }}.tar.gz
    dest: /tmp
    mode: 0777

- name: expand archive
  unarchive:
    src: /tmp/weewx-{{ weewx_version }}.tar.gz
    dest: /opt
    remote_src: True

- name: build 
  command: python3 ./setup.py build
  args:
    chdir: /opt/weewx-{{ weewx_version }}

- name: install
  become: true 
  command: python3 ./setup.py install
  args:
    chdir: /opt/weewx-{{ weewx_version }}

- name: create/overwrite config file from template
  template:
    src: "{{ weewx_config }}"
    dest: /home/{{ weewx_user }}/weewx.conf
    owner: "{{ weewx_user }}"
    mode: 0664

- name: ensure there is an archive directory to hold the SQLite database
  file:
    path: /home/{{ weewx_user }}/archive
    state: directory
    mode: 0775

- name: ensure there is an extensions directory in the weewx home
  file:
    path: /home/{{ weewx_user }}/extensions
    state: directory
    mode: 0775

- name: set owner on {{ weewx_user }} home directory
  file:
    path: /home/{{ weewx_user }}
    owner: "{{ weewx_user }}"
    group: "{{ weewx_user }}"
    recurse: yes

- name: create init.d startup script
  command: cp /home/{{ weewx_user }}/util/init.d/weewx.debian /etc/init.d/weewx
  notify:
    restart weewx

- name: set permissions on init.d startup script
  command: chmod +x /etc/init.d/weewx
  notify:
    restart weewx

- name: configure init.d startup script
  command: update-rc.d weewx defaults 98
  notify:
    restart weewx

- name: modify sudoers file to allow {{ weewx_user }} to stop/start service
  blockinfile:
    path: /etc/sudoers
    block: |
      %weewx ALL=NOPASSWD: /usr/sbin/service weewx stop
      %weewx ALL=NOPASSWD: /usr/sbin/service weewx start