---
- include_vars: group_vars/all
- name: create backup directory
  file:
    path: /home/{{ weewx_user }}/backup
    state: directory
    owner: "{{ weewx_user }}"
    group: "{{ weewx_user }}"
    mode: 0775
  when: backup == 'true'

- name: clone weewx_backup into backup directory
  git:
    repo: https://github.com/digitalbear/weewx.backup.git
    dest: /home/{{ weewx_user }}/backup
  when: backup == 'true'

- name: configure crontab to run backup script every day around 2 am
  cron:
    name: "weewx backup"
    hour: "2"
    minute: "15"
    user: "{{ weewx_user }}"
    job: /home/{{ weewx_user }}/backup/weewx_backup.sh > /home/{{ weewx_user }}/backup/weewx_backup.log 2>&1
  when: backup == 'true'
