- include_vars: group_vars/all

- name: install apache2
  package: 
    name: apache2
    state: present
    
- name: apache2 config
  command: sudo cp /home/{{ weewx_user }}/util/apache/conf.d/weewx.conf /etc/apache2/conf.d/weewx.conf