- include_vars: group_vars/all

- name: install nginx
  package: 
    name: apache2
    state: present
    
- name: nginx config 
  command: sudo cp /home/{{ weewx_user }}/util/apache/conf.d/weewx.conf /etc/apache2/conf.d